name: Merge Test to Prod

on:
  workflow_run:
    workflows: ["Nasazování do Testovacího prostředí"]
    types:
      - completed

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Merge test into prod
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git fetch origin
          git checkout prod
          git merge origin/test --no-ff -m "Merge branch 'test' into 'prod'"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} prod
